services:
  nginx:
    image: node:24.19.0-alpine@sha256:d32cdf619f63fe0471182d08996dd516c6275bb5fd31ae06e55a570bd9e1ad43
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`node.localhost`)"
      - "traefik.http.services.node.loadbalancer.server.port=3000"

networks:
  traefik-proxy:
    external: true
