services:
  nginx:
    image: nginx:1.30.4-alpine-slim@sha256:ddde39c6e51f02fde7410c2e9c234cf2d0a4c7bdbbe176aeb37d8ad7ab4eb58c
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`static.localhost`)"
      - "traefik.http.services.static.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true
